# Generated by Django 3.0.6 on 2020-06-07 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('priority', models.CharField(default='', max_length=8)),
                ('type', models.CharField(default='', max_length=20)),
                ('duedate', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 7, 15, 30, 32, 518626))),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
